# -*- coding: utf-8 -*-
"""Projeto1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aG6hLGFvK4bQFD1UL1Dk3MhlQB5ZS9n7
"""

# Programa de calculadora simples

print("Bem-vindo à calculadora!")

#Recebendo dois números do usuário e convertendo para float
numero1 = float(input("Digite o primeiro número: "))
numero2 = float(input("Digite o segundo número: "))

# Laço de repetição para permitir várias operações
while True:
  # Mostrar opções de operações para o usuário escolher
    print("\nEscolha a operação que deseja realizar:")
    print("1 - Soma (+)")
    print("2 - Subtração (-)")
    print("3 - Multiplicação (*)")
    print("4 - Divisão (/)")
    print("5 - Sair")

    opcao = input("Digite o número da operação: ")

# Condicional para realizar a operação escolhida
    if opcao == "1":
        resultado = numero1 + numero2
        print(f"Resultado da soma: {resultado}")
    elif opcao == "2":
        resultado = numero1 - numero2
        print(f"Resultado da subtração: {resultado}")
    elif opcao == "3":
        resultado = numero1 * numero2
        print(f"Resultado da multiplicação: {resultado}")
    elif opcao == "4":
        if numero2 != 0:
            resultado = numero1 / numero2
            print(f"Resultado da divisão: {resultado}")
        else:
            print("Erro: Não é possível dividir por zero.")
    elif opcao == "5":
        print("Encerrando a calculadora. Até mais!")
        break
    else:
        print("Opção inválida. Por favor, escolha uma opção correta.")